#pragma once
#include "Config.h"

#include <math.h>
#include <limits>


namespace rum
{
	/* float */
	#if ((__PRECISION_LEVEL_EROS__) == __PRECISION_LEVEL_LOW__)
	using real = float;

	#define EROS_REAL_MIN FLT_MIN
	#define EROS_REAL_MAX FLT_MAX

	#define EROS_REAL_PRECISION_DEZIMAL_DIG	FLT_DECIMAL_DIG
	#define EROS_REAL_PRECISION_DIG			FLT_DIG
	#define EROS_REAL_MANT_DIG				FLT_MANT_DIG

	#define EROS_REAL_EPSILON				FLT_EPSILON
	#define EROS_REAL_MAX_10_EXP			FLT_MAX_10_EXP
	#define EROS_REAL_MAX_EXP				FLT_MAX_EXP
	#define EROS_REAL_MIN_10_EXP			FLT_MIN_10_EXP
	#define EROS_REAL_MIN_EXP				FLT_MIN_EXP
	#define EROS_REAL_MIN_POS_VALUE			FLT_TRUE_MIN

	// GLM
	/*#define GLM_PRECISION_MEDIUMP_FLOAT
	#define GLM_PRECISION_MEDIUMP_DOUBLE
	#define GLM_PRECISION_MEDIUMP_INT
	#define GLM_PRECISION_MEDIUMP_UINT*/

	/* double */
	#elif ((__PRECISION_LEVEL_EROS__) == __PRECISION_LEVEL_MED__)
	using real = double;

	#define EROS_REAL_MIN DBL_MIN
	#define EROS_REAL_MAX DBL_MAX

	#define EROS_REAL_PRECISION_DEZIMAL_DIG	DBL_DECIMAL_DIG
	#define EROS_REAL_PRECISION_DIG			DBL_DIG
	#define EROS_REAL_MANT_DIG				DBL_MANT_DIG

	#define EROS_REAL_EPSILON				DBL_EPSILON
	#define EROS_REAL_MAX_10_EXP			DBL_MAX_10_EXP
	#define EROS_REAL_MAX_EXP				DBL_MAX_EXP
	#define EROS_REAL_MIN_10_EXP			DBL_MIN_10_EXP
	#define EROS_REAL_MIN_EXP				DBL_MIN_EXP
	#define EROS_REAL_MIN_POS_VALUE			DBL_TRUE_MIN

	// GLM
	#define GLM_PRECISION_MEDIUMP_FLOAT
	#define GLM_PRECISION_MEDIUMP_DOUBLE
	#define GLM_PRECISION_MEDIUMP_INT
	#define GLM_PRECISION_MEDIUMP_UINT



	/* long double */
	#else
	using real = long double;

	#define EROS_REAL_MIN LDBL_MIN
	#define EROS_REAL_MAX LDBL_MAX

	#define EROS_REAL_PRECISION_DEZIMAL_DIG	LDBL_DIG
	#define EROS_REAL_PRECISION_DIG			LDBL_DIG
	#define EROS_REAL_MANT_DIG				LDBL_MANT_DIG

	#define EROS_REAL_EPSILON				LDBL_EPSILON
	#define EROS_REAL_MAX_10_EXP			LDBL_MAX_10_EXP
	#define EROS_REAL_MAX_EXP				LDBL_MAX_EXP
	#define EROS_REAL_MIN_10_EXP			LDBL_MIN_10_EXP
	#define EROS_REAL_MIN_EXP				LDBL_MIN_EXP
	#define EROS_REAL_MIN_POS_VALUE			LDBL_TRUE_MIN

	// GLM
	#define GLM_PRECISION_HIGHP_FLOAT
	#define GLM_PRECISION_HIGHP_DOUBLE
	#define GLM_PRECISION_HIGHP_INT
	#define GLM_PRECISION_HIGHP_UINT

	#endif // __PRECISION_LEVEL_EROS__
}