#pragma once
#include <cmath>
#include <limits>

#define R3D_PRECISION_LEVEL_LOW 0
#define R3D_PRECISION_LEVEL_MED 1
#define R3D_PRECISION_LEVEL_HIGH 2


#define R3D_CURRENT_PRECISION_LEVEL R3D_PRECISION_LEVEL_LOW

namespace r3
{
	/* float */
	#if ((R3D_CURRENT_PRECISION_LEVEL) == R3D_PRECISION_LEVEL_LOW)
	using real = float;

	// GLM
	/*#define GLM_PRECISION_MEDIUMP_FLOAT
	#define GLM_PRECISION_MEDIUMP_DOUBLE
	#define GLM_PRECISION_MEDIUMP_INT
	#define GLM_PRECISION_MEDIUMP_UINT*/

	/* double */
	#elif ((R3D_CURRENT_PRECISION_LEVEL) == R3D_PRECISION_LEVEL_LOW)
	using real = double;

	// GLM
	#define GLM_PRECISION_MEDIUMP_FLOAT
	#define GLM_PRECISION_MEDIUMP_DOUBLE
	#define GLM_PRECISION_MEDIUMP_INT
	#define GLM_PRECISION_MEDIUMP_UINT

	/* long double */
	#else
	using real = long double;

	// GLM
	#define GLM_PRECISION_HIGHP_FLOAT
	#define GLM_PRECISION_HIGHP_DOUBLE
	#define GLM_PRECISION_HIGHP_INT
	#define GLM_PRECISION_HIGHP_UINT

	#endif // __PRECISION_LEVEL_EROS__
}